# -*- coding: utf-8 -*-
import json
import os

shlokas = [
    {
        "shloka_number": 1,
        "full_sanskrit": "ॐ भद्रं कर्णेभिः शृणुयाम देवा भद्रं पश्येमाक्षभिर्यजत्राः । स्थिरैरङ्गैस्तुष्टुवांसस्तनूभिर्व्यशेम देवहितं यदायुः ॥ स्वस्ति न इन्द्रो वृद्धश्रवाः स्वस्ति नः पूषा विश्ववेदाः । स्वस्ति नस्ताक्षर्यो अरिष्टनेमिः स्वस्ति नो बृहस्पतिर्दधातु ॥ ॐ शान्तिः शान्तिः शान्तिः ॥",
        "sandhi_split_sanskrit": "ॐ भद्रम् कर्णेभिः शृणुयाम देवाः भद्रम् पश्येम अक्षभिः यजत्राः । स्थिरैः अङ्गैः तुष्टुवांसः तनूभिः व्यशेम देवहितम् यत् आयुः ॥ स्वस्ति नः इन्द्रः वृद्ध-श्रवाः स्वस्ति नः पूषा विश्व-वेदाः । स्वस्ति नः तार्क्ष्यः अरिष्ट-नेमिः स्वस्ति नः बृहस्पतिः दधातु ॥ ॐ शान्तिः शान्तिः शान्तिः ॥",
        "iast_transliteration": "oṃ bhadraṃ karṇebhiḥ śṛṇuyāma devā bhadraṃ paśyemākṣabhiryajatrāḥ | sthirairaṅgaistuṣṭuvāṃsastanūbhirvyaśema devahitaṃ yadāyuḥ || svasti na indro vṛddhaśravāḥ svasti naḥ pūṣā viśvavedāḥ | svasti nastākṣaryo ariṣṭanemiḥ svasti no bṛhaspatirdadhātu || oṃ śāntiḥ śāntiḥ śāntiḥ ||",
        "meaning_english": "Om. O Gods, may we hear with our ears what is auspicious. May we see with our eyes what is auspicious, O worshipful ones. May we enjoy the life allotted to us by the Gods, offering our praise with our bodies and limbs firm. May Indra of great fame bestow auspiciousness on us. May Pushan, the all-knowing, bestow auspiciousness on us. May Tarkshya, of unhindered path, bestow auspiciousness on us. May Brihaspati bestow auspiciousness on us. Om Peace! Peace! Peace!",
        "meaning_hindi": None,
        "audio_start_ms": 10000,
        "audio_end_ms": 20000,
        "padas": [
            {"sanskrit_combined": "ॐ", "sanskrit_split": "ॐ", "iast": "oṃ", "meaning": "Om"},
            {"sanskrit_combined": "भद्रं", "sanskrit_split": "भद्रम्", "iast": "bhadraṃ", "meaning": "Auspicious"},
            {"sanskrit_combined": "कर्णेभिः", "sanskrit_split": "कर्णेभिः", "iast": "karṇebhiḥ", "meaning": "With ears"},
            {"sanskrit_combined": "शृणुयाम", "sanskrit_split": "शृणुयाम", "iast": "śṛṇuyāma", "meaning": "May we hear"},
            {"sanskrit_combined": "देवा", "sanskrit_split": "देवाः", "iast": "devā", "meaning": "O Gods"},
            {"sanskrit_combined": "भद्रं", "sanskrit_split": "भद्रम्", "iast": "bhadraṃ", "meaning": "Auspicious"},
            {"sanskrit_combined": "पश्येमाक्षभिर्यजत्राः", "sanskrit_split": "पश्येम + अक्षभिः + यजत्राः", "iast": "paśyemākṣabhiryajatrāḥ", "meaning": "May we see with eyes, O worshipful ones"},
            {"sanskrit_combined": "स्थिरैरङ्गैस्तुष्टुवांसस्तनूभिर्व्यशेम", "sanskrit_split": "स्थिरैः + अङ्गैः + तुष्टुवांसः + तनूभिः + व्यशेम", "iast": "sthirairaṅgaistuṣṭuvāṃsastanūbhirvyaśema", "meaning": "With firm limbs praising, may we enjoy"},
            {"sanskrit_combined": "देवहितं", "sanskrit_split": "देव-हितम्", "iast": "devahitaṃ", "meaning": "Allotted by Gods"},
            {"sanskrit_combined": "यदायुः", "sanskrit_split": "यत् + आयुः", "iast": "yadāyuḥ", "meaning": "What life"},
            {"sanskrit_combined": "स्वस्ति", "sanskrit_split": "स्वस्ति", "iast": "svasti", "meaning": "Auspiciousness"},
            {"sanskrit_combined": "न", "sanskrit_split": "नः", "iast": "na", "meaning": "To us"},
            {"sanskrit_combined": "इन्द्रो", "sanskrit_split": "इन्द्रः", "iast": "indro", "meaning": "Indra"},
            {"sanskrit_combined": "वृद्धश्रवाः", "sanskrit_split": "वृद्ध-श्रवाः", "iast": "vṛddhaśravāḥ", "meaning": "Of great fame"},
            {"sanskrit_combined": "स्वस्ति", "sanskrit_split": "स्वस्ति", "iast": "svasti", "meaning": "Auspiciousness"},
            {"sanskrit_combined": "नः", "sanskrit_split": "नः", "iast": "naḥ", "meaning": "To us"},
            {"sanskrit_combined": "पूषा", "sanskrit_split": "पूषा", "iast": "pūṣā", "meaning": "Pushan"},
            {"sanskrit_combined": "विश्ववेदाः", "sanskrit_split": "विश्व-वेदाः", "iast": "viśvavedāḥ", "meaning": "All-knowing"},
            {"sanskrit_combined": "स्वस्ति", "sanskrit_split": "स्वस्ति", "iast": "svasti", "meaning": "Auspiciousness"},
            {"sanskrit_combined": "नस्ताक्षर्यो", "sanskrit_split": "नः + तार्क्ष्यः", "iast": "nastākṣaryo", "meaning": "To us Tarkshya"},
            {"sanskrit_combined": "अरिष्टनेमिः", "sanskrit_split": "अरिष्ट-नेमिः", "iast": "ariṣṭanemiḥ", "meaning": "Unhindered path"},
            {"sanskrit_combined": "स्वस्ति", "sanskrit_split": "स्वस्ति", "iast": "svasti", "meaning": "Auspiciousness"},
            {"sanskrit_combined": "नो", "sanskrit_split": "नः", "iast": "no", "meaning": "To us"},
            {"sanskrit_combined": "बृहस्पतिर्दधातु", "sanskrit_split": "बृहस्पतिः + दधातु", "iast": "bṛhaspatirdadhātu", "meaning": "Brihaspati may bestow"},
            {"sanskrit_combined": "ॐ", "sanskrit_split": "ॐ", "iast": "oṃ", "meaning": "Om"},
            {"sanskrit_combined": "शान्तिः", "sanskrit_split": "शान्तिः", "iast": "śāntiḥ", "meaning": "Peace"},
            {"sanskrit_combined": "शान्तिः", "sanskrit_split": "शान्तिः", "iast": "śāntiḥ", "meaning": "Peace"},
            {"sanskrit_combined": "शान्तिः", "sanskrit_split": "शान्तिः", "iast": "śāntiḥ", "meaning": "Peace"}
        ]
    },
    {
        "shloka_number": 2,
        "full_sanskrit": "ॐ देवा ह वै स्वर्गं लोकमायंस्ते देवा रुद्रमपृच्छन् को भवानिति । सोऽब्रवीदहमेकः प्रथममासं वर्तामि च भविष्यामि च नान्यः कश्चिन्मत्तो व्यतिरिक्त इति ।",
        "sandhi_split_sanskrit": "ॐ देवाः ह वै स्वर्गम् लोकम् आयन् ते देवाः रुद्रम् अपृच्छन् कः भवान् इति । सः अब्रवीत् अहम् एकः प्रथमम् आसम् वर्तामि च भविष्यामि च न अन्यः कश्चित् मत्तः व्यतिरिक्तः इति ।",
        "iast_transliteration": "oṃ devā ha vai svargaṃ lokamāyaṃste devā rudramapṛcchan ko bhavāniti | so'bravīdahamekaḥ prathamamāsaṃ vartāmi ca bhaviṣyāmi ca nānyaḥ kaścinmatto vyatirikta iti |",
        "meaning_english": "Om. Once the Gods went to the heavenly world. The Gods asked Rudra, 'Who are you?' He replied, 'I alone was in the beginning, I exist now, and I will be in the future. There is no one else distinct from me.'",
        "meaning_hindi": None,
        "audio_start_ms": 20000,
        "audio_end_ms": 30000,
        "padas": [
            {"sanskrit_combined": "ॐ", "sanskrit_split": "ॐ", "iast": "oṃ", "meaning": "Om"},
            {"sanskrit_combined": "देवा", "sanskrit_split": "देवाः", "iast": "devā", "meaning": "Gods"},
            {"sanskrit_combined": "ह", "sanskrit_split": "ह", "iast": "ha", "meaning": "Indeed"},
            {"sanskrit_combined": "वै", "sanskrit_split": "वै", "iast": "vai", "meaning": "Verily"},
            {"sanskrit_combined": "स्वर्गं", "sanskrit_split": "स्वर्गम्", "iast": "svargaṃ", "meaning": "Heavenly"},
            {"sanskrit_combined": "लोकमायंस्ते", "sanskrit_split": "लोकम् + आयन् + ते", "iast": "lokamāyaṃste", "meaning": "World they went"},
            {"sanskrit_combined": "देवा", "sanskrit_split": "देवाः", "iast": "devā", "meaning": "Gods"},
            {"sanskrit_combined": "रुद्रमपृच्छन्", "sanskrit_split": "रुद्रम् + अपृच्छन्", "iast": "rudramapṛcchan", "meaning": "Asked Rudra"},
            {"sanskrit_combined": "को", "sanskrit_split": "कः", "iast": "ko", "meaning": "Who"},
            {"sanskrit_combined": "भवानिति", "sanskrit_split": "भवान् + इति", "iast": "bhavāniti", "meaning": "You thus"},
            {"sanskrit_combined": "सोऽब्रवीदहमेकः", "sanskrit_split": "सः + अब्रवीत् + अहम् + एकः", "iast": "so'bravīdahamekaḥ", "meaning": "He replied I one"},
            {"sanskrit_combined": "प्रथममासं", "sanskrit_split": "प्रथमम् + आसम्", "iast": "prathamamāsaṃ", "meaning": "Was in the beginning"},
            {"sanskrit_combined": "वर्तामि", "sanskrit_split": "वर्तामि", "iast": "vartāmi", "meaning": "Exist"},
            {"sanskrit_combined": "च", "sanskrit_split": "च", "iast": "ca", "meaning": "And"},
            {"sanskrit_combined": "भविष्यामि", "sanskrit_split": "भविष्यामि", "iast": "bhaviṣyāmi", "meaning": "Will be"},
            {"sanskrit_combined": "च", "sanskrit_split": "च", "iast": "ca", "meaning": "And"},
            {"sanskrit_combined": "नान्यः", "sanskrit_split": "न + अन्यः", "iast": "nānyaḥ", "meaning": "Not other"},
            {"sanskrit_combined": "कश्चिन्मत्तो", "sanskrit_split": "कश्चित् + मत्तः", "iast": "kaścinmatto", "meaning": "Anyone than me"},
            {"sanskrit_combined": "व्यतिरिक्त", "sanskrit_split": "व्यतिरिक्तः", "iast": "vyatirikta", "meaning": "Distinct"},
            {"sanskrit_combined": "इति", "sanskrit_split": "इति", "iast": "iti", "meaning": "Thus"}
        ]
    },
    {
        "shloka_number": 3,
        "full_sanskrit": "सोऽन्तरादन्तरं प्राविशत् दिशश्चान्तरं प्राविशत् सोऽहं नित्यानित्यौ व्यक्ताव्यक्तौ ब्रह्माब्रह्मणौ प्राञ्चः प्रत्यञ्चः । अहमेव प्राची दिगहं दक्षिणा दिगहं प्रतीची दिगहमुदीची दिगहमिमा दिशश्चोर्ध्वा दिशश्चाहं विरूपाक्षोऽहं विश्वरूपोऽहं पुमानपुमान् स्त्री चाहं सावर्त्र्यहं गायत्र्यहं त्रिष्टुब्जगत्यनुष्टुप् पङ्क्तिरहं छन्दोऽहं गार्हपत्यो दक्षिणाग्निराहवनीयोऽहं सत्योऽहं गौरहं गौर्यहं ज्येष्ठोऽहं श्रेष्ठोऽहं वरिष्ठोऽहमापोऽहं तेजोऽहमृग्यजुःसामाथर्वाङ्गिरसोऽहमक्षरमहं क्षरमहं गुह्योऽहं वनमहमरण्यमहमजोऽहं गुह्योऽहं सर्वं यच्च किञ्चिन्नाहं तदस्ति यच्चान्यत्सर्वमहमेव तन्मामेव विदित्वा सर्वमेव विन्दते तेन देवो देवत्वमश्नुते तेन स्वेन तेजसा ।",
        "sandhi_split_sanskrit": "सः अन्तरात् अन्तरम् प्राविशत् दिशः च अन्तरम् प्राविशत् सः अहम् नित्य-अनित्यौ व्यक्त-अव्यक्तौ ब्रह्म-अब्रह्मणौ प्राञ्चः प्रत्यञ्चः । अहम् एव प्राची दिक् अहम् दक्षिणा दिक् अहम् प्रतीची दिक् अहम् उदीची दिक् अहम् इमाः दिशः च ऊर्ध्वाः दिशः च अहम् विरूपाक्षः अहम् विश्वरूपः अहम् पुमान् अपुमान् स्त्री च अहम् सावित्री अहम् गायत्री अहम् त्रिष्टुप् जगती अनुष्टुप् पङ्क्तिः अहम् छन्दः अहम् गार्हपत्यः दक्षिणाग्निः आहवनीयः अहम् सत्यः अहम् गौः अहम् गौरी अहम् ज्येष्ठः अहम् श्रेष्ठः अहम् वरिष्ठः अहम् आपः अहम् तेजः अहम् ऋक्-यजुः-साम-अथर्वाङ्गिरसः अहम् अक्षरम् अहम् क्षरम् अहम् गुह्यः अहम् वनम् अहम् अरण्यम् अहम् अजः अहम् गुह्यः अहम् सर्वम् यत् च किञ्चित् न अहम् तत् अस्ति यत् च अन्यत् सर्वम् अहम् एव तत् माम् एव विदित्वा सर्वम् एव विन्दते तेन देवः देवत्वम् अश्नुते तेन स्वेन तेजसा ।",
        "iast_transliteration": "so'ntarādantaraṃ prāviśat diśaścāntaraṃ prāviśat so'haṃ nityānityau vyaktāvyaktau brahmābrahmaṇau prāñcaḥ pratyañcaḥ | ahameva prācī digahaṃ dakṣiṇā digahaṃ pratīcī digahamudīcī digahamimā diśaścordhvā diśaścāhaṃ virūpākṣo'haṃ viśvarūpo'haṃ pumānapumān strī cāhaṃ sāvrtryahaṃ gāyatryahaṃ triṣṭubjagatyanuṣṭup paṅktirahaṃ chando'haṃ gārhapatyo dakṣiṇāgnirāhavanīyo'haṃ satyo'haṃ gaurahaṃ gauryahaṃ jyeṣṭho'haṃ śreṣṭho'haṃ variṣṭho'hamāpo'haṃ tejo'hamṛgyajuḥsāmātharvāṅgiraso'hamakṣaramahaṃ kṣaramahaṃ guhyo'haṃ vanamahamaraṇyamahamajo'haṃ guhyo'haṃ sarvaṃ yacca kiñcinnāhaṃ tadasti yaccānyatsarvamahameva tanmāmeva viditvā sarvameva vindate tena devo devatvamaśnute tena svena tejasā |",
        "meaning_english": "He entered the inner from the inner. He entered the inner of the directions. He said: I am the eternal and the transient, the manifest and the unmanifest, the Brahman and non-Brahman, the East and the West. I alone am the eastern direction, I am the southern direction, I am the western direction, I am the northern direction, I am these directions and the upward directions. I am the one with uneven eyes, I am the universal form, I am male, eunuch, and female. I am Savitri, I am Gayatri, I am Tristubh, Jagati, Anustubh, Pankti. I am the meter. I am Garhapatya, Dakshinagni, Ahavaniya (fires). I am truth. I am cow, I am Gauri. I am the eldest, I am the best, I am the most excellent. I am water, I am light. I am Rig, Yajur, Sama, and Atharvangirasa. I am imperishable, I am perishable. I am secret. I am the forest, I am the wilderness. I am unborn. I am secret. Whatever is all, there is nothing that is not me. Whatever else is all, I am indeed that. By knowing me alone, one attains everything. Thus the god attains godhood by his own splendor.",
        "meaning_hindi": None,
        "audio_start_ms": 30000,
        "audio_end_ms": 40000,
        "padas": [
            {"sanskrit_combined": "सोऽन्तरादन्तरं", "sanskrit_split": "सः + अन्तरात् + अन्तरम्", "iast": "so'ntarādantaraṃ", "meaning": "He from inner the inner"},
            {"sanskrit_combined": "प्राविशत्", "sanskrit_split": "प्राविशत्", "iast": "prāviśat", "meaning": "Entered"},
            {"sanskrit_combined": "दिशश्चान्तरं", "sanskrit_split": "दिशः + च + अन्तरम्", "iast": "diśaścāntaraṃ", "meaning": "And directions' inner"},
            {"sanskrit_combined": "प्राविशत्", "sanskrit_split": "प्राविशत्", "iast": "prāviśat", "meaning": "Entered"},
            {"sanskrit_combined": "सोऽहं", "sanskrit_split": "सः + अहम्", "iast": "so'haṃ", "meaning": "He I am"},
            {"sanskrit_combined": "नित्यानित्यौ", "sanskrit_split": "नित्य-अनित्यौ", "iast": "nityānityau", "meaning": "Eternal and transient"},
            {"sanskrit_combined": "व्यक्ताव्यक्तौ", "sanskrit_split": "व्यक्त-अव्यक्तौ", "iast": "vyaktāvyaktau", "meaning": "Manifest and unmanifest"},
            {"sanskrit_combined": "ब्रह्माब्रह्मणौ", "sanskrit_split": "ब्रह्म-अब्रह्मणौ", "iast": "brahmābrahmaṇau", "meaning": "Brahman and non-Brahman"},
            {"sanskrit_combined": "प्राञ्चः", "sanskrit_split": "प्राञ्चः", "iast": "prāñcaḥ", "meaning": "East"},
            {"sanskrit_combined": "प्रत्यञ्चः", "sanskrit_split": "प्रत्यञ्चः", "iast": "pratyañcaḥ", "meaning": "West"},
            {"sanskrit_combined": "अहमेव", "sanskrit_split": "अहम् + एव", "iast": "ahameva", "meaning": "I alone"},
            {"sanskrit_combined": "प्राची", "sanskrit_split": "प्राची", "iast": "prācī", "meaning": "Eastern"},
            {"sanskrit_combined": "दिगहं", "sanskrit_split": "दिक् + अहम्", "iast": "digahaṃ", "meaning": "Direction I am"},
            {"sanskrit_combined": "दक्षिणा", "sanskrit_split": "दक्षिणा", "iast": "dakṣiṇā", "meaning": "Southern"},
            {"sanskrit_combined": "दिगहं", "sanskrit_split": "दिक् + अहम्", "iast": "digahaṃ", "meaning": "Direction I am"},
            {"sanskrit_combined": "प्रतीची", "sanskrit_split": "प्रतीची", "iast": "pratīcī", "meaning": "Western"},
            {"sanskrit_combined": "दिगहमुदीची", "sanskrit_split": "दिक् + अहम् + उदीची", "iast": "digahamudīcī", "meaning": "Direction I am northern"},
            {"sanskrit_combined": "दिगहमिमा", "sanskrit_split": "दिक् + अहम् + इमाः", "iast": "digahamimā", "meaning": "Direction I am these"},
            {"sanskrit_combined": "दिशश्चोर्ध्वा", "sanskrit_split": "दिशः + च + ऊर्ध्वाः", "iast": "diśaścordhvā", "meaning": "And directions upward"},
            {"sanskrit_combined": "दिशश्चाहं", "sanskrit_split": "दिशः + च + अहम्", "iast": "diśaścāhaṃ", "meaning": "And directions I am"},
            {"sanskrit_combined": "विरूपाक्षोऽहं", "sanskrit_split": "विरूपाक्षः + अहम्", "iast": "virūpākṣo'haṃ", "meaning": "Uneven-eyed I am"},
            {"sanskrit_combined": "विश्वरूपोऽहं", "sanskrit_split": "विश्वरूपः + अहम्", "iast": "viśvarūpo'haṃ", "meaning": "Universal form I am"},
            {"sanskrit_combined": "पुमानपुमान्", "sanskrit_split": "पुमान् + अपुमान्", "iast": "pumānapumān", "meaning": "Male and non-male"},
            {"sanskrit_combined": "स्त्री", "sanskrit_split": "स्त्री", "iast": "strī", "meaning": "Female"},
            {"sanskrit_combined": "चाहं", "sanskrit_split": "च + अहम्", "iast": "cāhaṃ", "meaning": "And I am"},
            {"sanskrit_combined": "सावर्त्र्यहं", "sanskrit_split": "सावित्री + अहम्", "iast": "sāvrtryahaṃ", "meaning": "Savitri I am"},
            {"sanskrit_combined": "गायत्र्यहं", "sanskrit_split": "गायत्री + अहम्", "iast": "gāyatryahaṃ", "meaning": "Gayatri I am"},
            {"sanskrit_combined": "त्रिष्टुब्जगत्यनुष्टुप्", "sanskrit_split": "त्रिष्टुप् + जगती + अनुष्टुप्", "iast": "triṣṭubjagatyanuṣṭup", "meaning": "Tristubh, Jagati, Anustubh"},
            {"sanskrit_combined": "पङ्क्तिरहं", "sanskrit_split": "पङ्क्तिः + अहम्", "iast": "paṅktirahaṃ", "meaning": "Pankti I am"},
            {"sanskrit_combined": "छन्दोऽहं", "sanskrit_split": "छन्दः + अहम्", "iast": "chando'haṃ", "meaning": "Meter I am"},
            {"sanskrit_combined": "गार्हपत्यो", "sanskrit_split": "गार्हपत्यः", "iast": "gārhapatyo", "meaning": "Garhapatya fire"},
            {"sanskrit_combined": "दक्षिणाग्निराहवनीयोऽहं", "sanskrit_split": "दक्षिणाग्निः + आहवनीयः + अहम्", "iast": "dakṣiṇāgnirāhavanīyo'haṃ", "meaning": "Dakshinagni, Ahavaniya I am"},
            {"sanskrit_combined": "सत्योऽहं", "sanskrit_split": "सत्यः + अहम्", "iast": "satyo'haṃ", "meaning": "Truth I am"},
            {"sanskrit_combined": "गौरहं", "sanskrit_split": "गौः + अहम्", "iast": "gaurahaṃ", "meaning": "Cow I am"},
            {"sanskrit_combined": "गौर्यहं", "sanskrit_split": "गौरी + अहम्", "iast": "gauryahaṃ", "meaning": "Gauri I am"},
            {"sanskrit_combined": "ज्येष्ठोऽहं", "sanskrit_split": "ज्येष्ठः + अहम्", "iast": "jyeṣṭho'haṃ", "meaning": "Eldest I am"},
            {"sanskrit_combined": "श्रेष्ठोऽहं", "sanskrit_split": "श्रेष्ठः + अहम्", "iast": "śreṣṭho'haṃ", "meaning": "Best I am"},
            {"sanskrit_combined": "वरिष्ठोऽहमापोऽहं", "sanskrit_split": "वरिष्ठः + अहम् + आपः + अहम्", "iast": "variṣṭho'hamāpo'haṃ", "meaning": "Most excellent I am, water I am"},
            {"sanskrit_combined": "तेजोऽहमृग्यजुःसामाथर्वाङ्गिरसोऽहमक्षरमहं", "sanskrit_split": "तेजः + अहम् + ऋक्-यजुः-साम-अथर्वाङ्गिरसः + अहम् + अक्षरम् + अहम्", "iast": "tejo'hamṛgyajuḥsāmātharvāṅgiraso'hamakṣaramahaṃ", "meaning": "Light I am, Rig, Yajur, Sama, Atharvangirasa I am, Imperishable I am"},
            {"sanskrit_combined": "क्षरमहं", "sanskrit_split": "क्षरम् + अहम्", "iast": "kṣaramahaṃ", "meaning": "Perishable I am"},
            {"sanskrit_combined": "गुह्योऽहं", "sanskrit_split": "गुह्यः + अहम्", "iast": "guhyo'haṃ", "meaning": "Secret I am"},
            {"sanskrit_combined": "वनमहमरण्यमहमजोऽहं", "sanskrit_split": "वनम् + अहम् + अरण्यम् + अहम् + अजः + अहम्", "iast": "vanamahamaraṇyamahamajo'haṃ", "meaning": "Forest I am, wilderness I am, unborn I am"},
            {"sanskrit_combined": "गुह्योऽहं", "sanskrit_split": "गुह्यः + अहम्", "iast": "guhyo'haṃ", "meaning": "Secret I am"},
            {"sanskrit_combined": "सर्वं", "sanskrit_split": "सर्वम्", "iast": "sarvaṃ", "meaning": "All"},
            {"sanskrit_combined": "यच्च", "sanskrit_split": "यत् + च", "iast": "yacca", "meaning": "Whatever"},
            {"sanskrit_combined": "किञ्चिन्नाहं", "sanskrit_split": "किञ्चित् + न + अहम्", "iast": "kiñcinnāhaṃ", "meaning": "Anything not I am"},
            {"sanskrit_combined": "तदस्ति", "sanskrit_split": "तत् + अस्ति", "iast": "tadasti", "meaning": "That is"},
            {"sanskrit_combined": "यच्चान्यत्सर्वमहमेव", "sanskrit_split": "यत् + च + अन्यत् + सर्वम् + अहम् + एव", "iast": "yaccānyatsarvamahameva", "meaning": "Whatever else is all I alone"},
            {"sanskrit_combined": "तन्मामेव", "sanskrit_split": "तत् + माम् + एव", "iast": "tanmāmeva", "meaning": "That me alone"},
            {"sanskrit_combined": "विदित्वा", "sanskrit_split": "विदित्वा", "iast": "viditvā", "meaning": "Knowing"},
            {"sanskrit_combined": "सर्वमेव", "sanskrit_split": "सर्वम् + एव", "iast": "sarvameva", "meaning": "Everything"},
            {"sanskrit_combined": "विन्दते", "sanskrit_split": "विन्दते", "iast": "vindate", "meaning": "Attains"},
            {"sanskrit_combined": "तेन", "sanskrit_split": "तेन", "iast": "tena", "meaning": "By that"},
            {"sanskrit_combined": "देवो", "sanskrit_split": "देवः", "iast": "devo", "meaning": "God"},
            {"sanskrit_combined": "देवत्वमश्नुते", "sanskrit_split": "देवत्वम् + अश्नुते", "iast": "devatvamaśnute", "meaning": "Attains godhood"},
            {"sanskrit_combined": "तेन", "sanskrit_split": "तेन", "iast": "tena", "meaning": "By that"},
            {"sanskrit_combined": "स्वेन", "sanskrit_split": "स्वेन", "iast": "svena", "meaning": "By own"},
            {"sanskrit_combined": "तेजसा", "sanskrit_split": "तेजसा", "iast": "tejasā", "meaning": "Splendor"}
        ]
    },
    {
        "shloka_number": 4,
        "full_sanskrit": "ततो ह वै ते देवा रुद्रमपृच्छन् । ते देवा रुद्रं स्तुवन्ति । ॐ भूर्भुवः सुवर्भूर्भुवः सुवर्भूर्भुवः सुवरिति । ते देवा ऊर्ध्वबाहवो रुद्रं स्तुवन्ति ॥ १॥",
        "sandhi_split_sanskrit": "ततः ह वै ते देवाः रुद्रम् अपृच्छन् । ते देवाः रुद्रम् स्तुवन्ति । ॐ भूः भुवः सुवः भूः भुवः सुवः भूः भुवः सुवः इति । ते देवाः ऊर्ध्व-बाहवः रुद्रम् स्तुवन्ति ॥ १॥",
        "iast_transliteration": "tato ha vai te devā rudramapṛcchan | te devā rudraṃ stuvanti | oṃ bhūrbhuvaḥ suvarbhūrbhuvaḥ suvarbhūrbhuvaḥ suvariti | te devā ūrdhvabāhavo rudraṃ stuvanti || 1||",
        "meaning_english": "Then indeed the Gods asked Rudra. Those Gods praised Rudra. Saying 'Om Bhur Bhuva Suvah Bhur Bhuva Suvah Bhur Bhuva Suvah'. Those Gods with raised arms praise Rudra. (1)",
        "meaning_hindi": None,
        "audio_start_ms": 40000,
        "audio_end_ms": 50000,
        "padas": [
            {"sanskrit_combined": "ततो", "sanskrit_split": "ततः", "iast": "tato", "meaning": "Then"},
            {"sanskrit_combined": "ह", "sanskrit_split": "ह", "iast": "ha", "meaning": "Indeed"},
            {"sanskrit_combined": "वै", "sanskrit_split": "वै", "iast": "vai", "meaning": "Verily"},
            {"sanskrit_combined": "ते", "sanskrit_split": "ते", "iast": "te", "meaning": "Those"},
            {"sanskrit_combined": "देवा", "sanskrit_split": "देवाः", "iast": "devā", "meaning": "Gods"},
            {"sanskrit_combined": "रुद्रमपृच्छन्", "sanskrit_split": "रुद्रम् + अपृच्छन्", "iast": "rudramapṛcchan", "meaning": "Asked Rudra"},
            {"sanskrit_combined": "ते", "sanskrit_split": "ते", "iast": "te", "meaning": "Those"},
            {"sanskrit_combined": "देवा", "sanskrit_split": "देवाः", "iast": "devā", "meaning": "Gods"},
            {"sanskrit_combined": "रुद्रं", "sanskrit_split": "रुद्रम्", "iast": "rudraṃ", "meaning": "To Rudra"},
            {"sanskrit_combined": "स्तुवन्ति", "sanskrit_split": "स्तुवन्ति", "iast": "stuvanti", "meaning": "Praise"},
            {"sanskrit_combined": "ॐ", "sanskrit_split": "ॐ", "iast": "oṃ", "meaning": "Om"},
            {"sanskrit_combined": "भूर्भुवः", "sanskrit_split": "भूः + भुवः", "iast": "bhūrbhuvaḥ", "meaning": "Bhur Bhuva"},
            {"sanskrit_combined": "सुवर्भूर्भुवः", "sanskrit_split": "सुवः + भूः + भुवः", "iast": "suvarbhūrbhuvaḥ", "meaning": "Suvah Bhur Bhuva"},
            {"sanskrit_combined": "सुवर्भूर्भुवः", "sanskrit_split": "सुवः + भूः + भुवः", "iast": "suvarbhūrbhuvaḥ", "meaning": "Suvah Bhur Bhuva"},
            {"sanskrit_combined": "सुवरिति", "sanskrit_split": "सुवः + इति", "iast": "suvariti", "meaning": "Suvah thus"},
            {"sanskrit_combined": "ते", "sanskrit_split": "ते", "iast": "te", "meaning": "Those"},
            {"sanskrit_combined": "देवा", "sanskrit_split": "देवाः", "iast": "devā", "meaning": "Gods"},
            {"sanskrit_combined": "ऊर्ध्वबाहवो", "sanskrit_split": "ऊर्ध्व-बाहवः", "iast": "ūrdhvabāhavo", "meaning": "With raised arms"},
            {"sanskrit_combined": "रुद्रं", "sanskrit_split": "रुद्रम्", "iast": "rudraṃ", "meaning": "Rudra"},
            {"sanskrit_combined": "स्तुवन्ति", "sanskrit_split": "स्तुवन्ति", "iast": "stuvanti", "meaning": "Praise"}
        ]
    },
    {
        "shloka_number": 5,
        "full_sanskrit": "ॐ यो वै रुद्रः स भगवान्यश्च ब्रह्मा तस्मै वै नमोनमः ॥ १॥ ... यो वै रुद्रः स भगवान्यच्च सर्वं तस्मै वै नमोनमः ॥ ३२॥",
        "sandhi_split_sanskrit": "ॐ यः वै रुद्रः सः भगवान् यः च ब्रह्मा तस्मै वै नमः नमः ॥ १॥ ... यः वै रुद्रः सः भगवान् यत् च सर्वम् तस्मै वै नमः नमः ॥ ३२॥",
        "iast_transliteration": "oṃ yo vai rudraḥ sa bhagavānyaśca brahmā tasmai vai namonamaḥ || 1|| ... yo vai rudraḥ sa bhagavānyacca sarvaṃ tasmai vai namonamaḥ || 32||",
        "meaning_english": "Om. He who is verily Rudra, He is Bhagavan (the Lord). He who is Brahma, to Him indeed, salutations again and again! ... He who is verily Rudra, He is Bhagavan. He who is everything, to Him indeed, salutations again and again! (salutations 1 to 32)",
        "meaning_hindi": None,
        "audio_start_ms": 50000,
        "audio_end_ms": 60000,
        "padas": [
            {"sanskrit_combined": "ॐ", "sanskrit_split": "ॐ", "iast": "oṃ", "meaning": "Om"},
            {"sanskrit_combined": "यो", "sanskrit_split": "यः", "iast": "yo", "meaning": "Who"},
            {"sanskrit_combined": "वै", "sanskrit_split": "वै", "iast": "vai", "meaning": "Verily"},
            {"sanskrit_combined": "रुद्रः", "sanskrit_split": "रुद्रः", "iast": "rudraḥ", "meaning": "Rudra"},
            {"sanskrit_combined": "स", "sanskrit_split": "सः", "iast": "sa", "meaning": "He"},
            {"sanskrit_combined": "भगवान्यश्च", "sanskrit_split": "भगवान् + यः + च", "iast": "bhagavānyaśca", "meaning": "Bhagavan and who"},
            {"sanskrit_combined": "ब्रह्मा", "sanskrit_split": "ब्रह्मा", "iast": "brahmā", "meaning": "Brahma"},
            {"sanskrit_combined": "तस्मै", "sanskrit_split": "तस्मै", "iast": "tasmai", "meaning": "To him"},
            {"sanskrit_combined": "वै", "sanskrit_split": "वै", "iast": "vai", "meaning": "Indeed"},
            {"sanskrit_combined": "नमोनमः", "sanskrit_split": "नमः + नमः", "iast": "namonamaḥ", "meaning": "Salutations again and again"}
        ]
    },
    {
        "shloka_number": 6,
        "full_sanskrit": "भूस्ते आदिर्मध्यं भुवः सुवस्ते शीर्षं विश्वरूपोऽसि । ब्रह्मैकस्त्वं द्वा सुवर्णा तयोरादित्यः पुरुषो महाञ्छुक आर्षभेयः । तस्मादुपसंहर्त्रे महाग्रासाय वै नमो नमः ।",
        "sandhi_split_sanskrit": "भूः ते आदिः मध्यम् भुवः सुवः ते शीर्षम् विश्वरूपः असि । ब्रह्मा एकः त्वम् द्वौ सुवर्णौ तयोः आदित्यः पुरुषः महान् शुकः आर्षभेयः । तस्मात् उपसंहर्त्रे महाग्रासाय वै नमः नमः ।",
        "iast_transliteration": "bhūste ādirmadhyaṃ bhuvaḥ suvaste śīrṣaṃ viśvarūpo'si | brahmaikastvaṃ dvā suvarṇā tayorādityaḥ puruṣo mahāñchuka ārṣabheyaḥ | tasmādupasaṃhartre mahāgrāsāya vai namo namaḥ |",
        "meaning_english": "'Bhu' is Your beginning, 'Bhuva' is the middle, 'Suvah' is Your head. You are the universal form. You are the one Brahma, the two golden (birds), of them, the sun, the great person, bright, descended from the Rishabha. Therefore to the withdrawer, to the great devourer, indeed salutations again and again.",
        "meaning_hindi": None,
        "audio_start_ms": 60000,
        "audio_end_ms": 70000,
        "padas": [
            {"sanskrit_combined": "भूस्ते", "sanskrit_split": "भूः + ते", "iast": "bhūste", "meaning": "Bhu is Your"},
            {"sanskrit_combined": "आदिर्मध्यं", "sanskrit_split": "आदिः + मध्यम्", "iast": "ādirmadhyaṃ", "meaning": "Beginning, middle"},
            {"sanskrit_combined": "भुवः", "sanskrit_split": "भुवः", "iast": "bhuvaḥ", "meaning": "Bhuva"},
            {"sanskrit_combined": "सुवस्ते", "sanskrit_split": "सुवः + ते", "iast": "suvaste", "meaning": "Suvah is Your"},
            {"sanskrit_combined": "शीर्षं", "sanskrit_split": "शीर्षम्", "iast": "śīrṣaṃ", "meaning": "Head"},
            {"sanskrit_combined": "विश्वरूपोऽसि", "sanskrit_split": "विश्वरूपः + असि", "iast": "viśvarūpo'si", "meaning": "Universal form You are"},
            {"sanskrit_combined": "ब्रह्मैकस्त्वं", "sanskrit_split": "ब्रह्मा + एकः + त्वम्", "iast": "brahmaikastvaṃ", "meaning": "Brahma one You"},
            {"sanskrit_combined": "द्वा", "sanskrit_split": "द्वौ", "iast": "dvā", "meaning": "Two"},
            {"sanskrit_combined": "सुवर्णा", "sanskrit_split": "सुवर्णौ", "iast": "suvarṇā", "meaning": "Golden"},
            {"sanskrit_combined": "तयोरादित्यः", "sanskrit_split": "तयोः + आदित्यः", "iast": "tayorādityaḥ", "meaning": "Of them the sun"},
            {"sanskrit_combined": "पुरुषो", "sanskrit_split": "पुरुषः", "iast": "puruṣo", "meaning": "Person"},
            {"sanskrit_combined": "महाञ्छुक", "sanskrit_split": "महान् + शुकः", "iast": "mahāñchuka", "meaning": "Great bright"},
            {"sanskrit_combined": "आर्षभेयः", "sanskrit_split": "आर्षभेयः", "iast": "ārṣabheyaḥ", "meaning": "Descended from Rishabha"},
            {"sanskrit_combined": "तस्मादुपसंहर्त्रे", "sanskrit_split": "तस्मात् + उपसंहर्त्रे", "iast": "tasmādupasaṃhartre", "meaning": "Therefore to the withdrawer"},
            {"sanskrit_combined": "महाग्रासाय", "sanskrit_split": "महाग्रासाय", "iast": "mahāgrāsāya", "meaning": "To the great devourer"},
            {"sanskrit_combined": "वै", "sanskrit_split": "वै", "iast": "vai", "meaning": "Indeed"},
            {"sanskrit_combined": "नमो", "sanskrit_split": "नमः", "iast": "namo", "meaning": "Salutations"},
            {"sanskrit_combined": "नमः", "sanskrit_split": "नमः", "iast": "namaḥ", "meaning": "Salutations"}
        ]
    },
    {
        "shloka_number": 7,
        "full_sanskrit": "हृदिस्था देवताः सर्वा हृदि प्राणाः प्रतिष्ठिताः । हृदि प्राणो निविष्टोऽयं यस्तृतीये महेश्वरे । तदेतदोमिति व्यापकमक्षरम् । तच्छुक्लं यच्छुक्लं तद्वैद्युतं यद्वैद्युतं तत्परं ब्रह्म यत्परं ब्रह्म स एको य एकः स रुद्रो यो रुद्रः स ईशानो य ईशानः स भगवान् महेश्वरः ॥ ३॥",
        "sandhi_split_sanskrit": "हृदि-स्थाः देवताः सर्वाः हृदि प्राणाः प्रतिष्ठिताः । हृदि प्राणः निविष्टः अयम् यः तृतीये महेश्वरे । तत् एतत् ओम् इति व्यापकम् अक्षरम् । तत् शुक्लम् यत् शुक्लम् तत् वैद्युतम् यत् वैद्युतम् तत् परम् ब्रह्म यत् परम् ब्रह्म सः एकः यः एकः सः रुद्रः यः रुद्रः सः ईशानः यः ईशानः सः भगवान् महेश्वरः ॥ ३॥",
        "iast_transliteration": "hṛdisthā devatāḥ sarvā hṛdi prāṇāḥ pratiṣṭhitāḥ | hṛdi prāṇo niviṣṭo'yaṃ yastṛtīye maheśvare | tadetadomiti vyāpakamakṣaram | tacchuklaṃ yacchuklaṃ tadvaidyutaṃ yadvaidyutaṃ tatparaṃ brahma yatparaṃ brahma sa eko ya ekaḥ sa rudro yo rudraḥ sa īśāno ya īśānaḥ sa bhagavān maheśvaraḥ || 3||",
        "meaning_english": "All gods are stationed in the heart. The vital breaths are established in the heart. This vital breath is entered into the heart, which is in the third, in Mahesvara. That is this Om, the all-pervading imperishable. That which is white, that which is white is lightning; that which is lightning is the supreme Brahman; that which is the supreme Brahman is one; he who is one is Rudra; he who is Rudra is Ishana; he who is Ishana is Bhagavan Mahesvara. (3)",
        "meaning_hindi": None,
        "audio_start_ms": 70000,
        "audio_end_ms": 80000,
        "padas": [
            {"sanskrit_combined": "हृदिस्था", "sanskrit_split": "हृदि-स्थाः", "iast": "hṛdisthā", "meaning": "Stationed in heart"},
            {"sanskrit_combined": "देवताः", "sanskrit_split": "देवताः", "iast": "devatāḥ", "meaning": "Gods"},
            {"sanskrit_combined": "सर्वा", "sanskrit_split": "सर्वाः", "iast": "sarvā", "meaning": "All"},
            {"sanskrit_combined": "हृदि", "sanskrit_split": "हृदि", "iast": "hṛdi", "meaning": "In heart"},
            {"sanskrit_combined": "प्राणाः", "sanskrit_split": "प्राणाः", "iast": "prāṇāḥ", "meaning": "Vital breaths"},
            {"sanskrit_combined": "प्रतिष्ठिताः", "sanskrit_split": "प्रतिष्ठिताः", "iast": "pratiṣṭhitāḥ", "meaning": "Established"},
            {"sanskrit_combined": "हृदि", "sanskrit_split": "हृदि", "iast": "hṛdi", "meaning": "In heart"},
            {"sanskrit_combined": "प्राणो", "sanskrit_split": "प्राणः", "iast": "prāṇo", "meaning": "Vital breath"},
            {"sanskrit_combined": "निविष्टोऽयं", "sanskrit_split": "निविष्टः + अयम्", "iast": "niviṣṭo'yaṃ", "meaning": "Is entered this"},
            {"sanskrit_combined": "यस्तृतीये", "sanskrit_split": "यः + तृतीये", "iast": "yastṛtīye", "meaning": "Which in the third"},
            {"sanskrit_combined": "महेश्वरे", "sanskrit_split": "महेश्वरे", "iast": "maheśvare", "meaning": "In Mahesvara"},
            {"sanskrit_combined": "तदेतदोमिति", "sanskrit_split": "तत् + एतत् + ओम् + इति", "iast": "tadetadomiti", "meaning": "That this Om thus"},
            {"sanskrit_combined": "व्यापकमक्षरम्", "sanskrit_split": "व्यापकम् + अक्षरम्", "iast": "vyāpakamakṣaram", "meaning": "All-pervading imperishable"},
            {"sanskrit_combined": "तच्छुक्लं", "sanskrit_split": "तत् + शुक्लम्", "iast": "tacchuklaṃ", "meaning": "That white"},
            {"sanskrit_combined": "यच्छुक्लं", "sanskrit_split": "यत् + शुक्लम्", "iast": "yacchuklaṃ", "meaning": "Which white"},
            {"sanskrit_combined": "तद्वैद्युतं", "sanskrit_split": "तत् + वैद्युतम्", "iast": "tadvaidyutaṃ", "meaning": "That lightning"},
            {"sanskrit_combined": "यद्वैद्युतं", "sanskrit_split": "यत् + वैद्युतम्", "iast": "yadvaidyutaṃ", "meaning": "Which lightning"},
            {"sanskrit_combined": "तत्परं", "sanskrit_split": "तत् + परम्", "iast": "tatparaṃ", "meaning": "That supreme"},
            {"sanskrit_combined": "ब्रह्म", "sanskrit_split": "ब्रह्म", "iast": "brahma", "meaning": "Brahman"},
            {"sanskrit_combined": "यत्परं", "sanskrit_split": "यत् + परम्", "iast": "yatparaṃ", "meaning": "Which supreme"},
            {"sanskrit_combined": "ब्रह्म", "sanskrit_split": "ब्रह्म", "iast": "brahma", "meaning": "Brahman"},
            {"sanskrit_combined": "स", "sanskrit_split": "सः", "iast": "sa", "meaning": "He"},
            {"sanskrit_combined": "एको", "sanskrit_split": "एकः", "iast": "eko", "meaning": "One"},
            {"sanskrit_combined": "य", "sanskrit_split": "यः", "iast": "ya", "meaning": "Who"},
            {"sanskrit_combined": "एकः", "sanskrit_split": "एकः", "iast": "ekaḥ", "meaning": "One"},
            {"sanskrit_combined": "स", "sanskrit_split": "सः", "iast": "sa", "meaning": "He"},
            {"sanskrit_combined": "रुद्रो", "sanskrit_split": "रुद्रः", "iast": "rudro", "meaning": "Rudra"},
            {"sanskrit_combined": "यो", "sanskrit_split": "यः", "iast": "yo", "meaning": "Who"},
            {"sanskrit_combined": "रुद्रः", "sanskrit_split": "रुद्रः", "iast": "rudraḥ", "meaning": "Rudra"},
            {"sanskrit_combined": "स", "sanskrit_split": "सः", "iast": "sa", "meaning": "He"},
            {"sanskrit_combined": "ईशानो", "sanskrit_split": "ईशानः", "iast": "īśāno", "meaning": "Ishana"},
            {"sanskrit_combined": "य", "sanskrit_split": "यः", "iast": "ya", "meaning": "Who"},
            {"sanskrit_combined": "ईशानः", "sanskrit_split": "ईशानः", "iast": "īśānaḥ", "meaning": "Ishana"},
            {"sanskrit_combined": "स", "sanskrit_split": "सः", "iast": "sa", "meaning": "He"},
            {"sanskrit_combined": "भगवान्", "sanskrit_split": "भगवान्", "iast": "bhagavān", "meaning": "Bhagavan"},
            {"sanskrit_combined": "महेश्वरः", "sanskrit_split": "महेश्वरः", "iast": "maheśvaraḥ", "meaning": "Mahesvara"}
        ]
    },
    {
        "shloka_number": 8,
        "full_sanskrit": "अथ कस्मादुच्यत ओङ्कारो यस्मादुच्चार्यमाण एव प्राणानूर्ध्वमुत्क्रामयति तस्मादुच्यत ओङ्कारः । अथ कस्मादुच्यते प्रणवो यस्मादुच्चार्यमाण एव ऋग्यजुःसामाथर्वाङ्गिरसो ब्रह्म ब्राह्मणेभ्यः प्रणामयति तस्मादुच्यते प्रणवः । अथ कस्मादुच्यते सर्वव्यापी यस्मादुच्चार्यमाण एव सर्वान् लोकान् व्याप्नोति तस्मादुच्यते सर्वव्यापी । अथ कस्मादुच्यतेऽनन्तो यस्मादुच्चार्यमाण एवाद्यन्तं नोपलभ्यते तस्मादुच्यतेऽनन्तः । अथ कस्मादुच्यते तारं यस्मादुच्चार्यमाण एव गर्भजन्मव्याधिजरामरणसंसारमहाभयात्तारयति त्रायते च तस्मादुच्यते तारम् ।",
        "sandhi_split_sanskrit": "अथ कस्मात् उच्यते ओङ्कारः यस्मात् उच्चार्यमाणः एव प्राणान् ऊर्ध्वम् उत्क्रामयति तस्मात् उच्यते ओङ्कारः । अथ कस्मात् उच्यते प्रणवः यस्मात् उच्चार्यमाणः एव ऋक्-यजुः-साम-अथर्वाङ्गिरसः ब्रह्म ब्राह्मणेभ्यः प्रणामयति तस्मात् उच्यते प्रणवः । अथ कस्मात् उच्यते सर्वव्यापी यस्मात् उच्चार्यमाणः एव सर्वान् लोकान् व्याप्नोति तस्मात् उच्यते सर्वव्यापी । अथ कस्मात् उच्यते अनन्तः यस्मात् उच्चार्यमाणः एव आदि-अन्तम् न उपलभ्यते तस्मात् उच्यते अनन्तः । अथ कस्मात् उच्यते तारम् यस्मात् उच्चार्यमाणः एव गर्भ-जन्म-व्याधि-जरा-मरण-संसार-महा-भयात् तारयति त्रायते च तस्मात् उच्यते तारम् ।",
        "iast_transliteration": "atha kasmāducyata oṅkāro yasmāduccāryamāṇa eva prāṇānūrdhvamutkrāmayati tasmāducyata oṅkāraḥ | atha kasmāducyate praṇavo yasmāduccāryamāṇa eva ṛgyajuḥsāmātharvāṅgiraso brahma brāhmaṇebhyaḥ praṇāmayati tasmāducyate praṇavaḥ | atha kasmāducyate sarvavyāpī yasmāduccāryamāṇa eva sarvān lokān vyāpnoti tasmāducyate sarvavyāpī | atha kasmāducyate'nanto yasmāduccāryamāṇa evādyantaṃ nopalabhyate tasmāducyate'nantaḥ | atha kasmāducyate tāraṃ yasmāduccāryamāṇa eva garbhajanmavyādhijarāmaraṇasaṃsāramahābhayāttārayati trāyate ca tasmāducyate tāram |",
        "meaning_english": "Now why is it called Omkara? Because being pronounced, it sends the vital breaths upward, therefore it is called Omkara. Now why is it called Pranava? Because being pronounced, it makes the Brahman of Rig, Yajur, Sama, and Atharvangirasa bow down to the Brahmanas, therefore it is called Pranava. Now why is it called All-Pervading? Because being pronounced, it pervades all worlds, therefore it is called All-Pervading. Now why is it called Endless? Because being pronounced, its beginning and end are not found, therefore it is called Endless. Now why is it called Tara? Because being pronounced, it helps one cross over and protects from the great fear of conception, birth, disease, old age, death, and worldly existence, therefore it is called Tara.",
        "meaning_hindi": None,
        "audio_start_ms": 80000,
        "audio_end_ms": 90000,
        "padas": [
            {"sanskrit_combined": "अथ", "sanskrit_split": "अथ", "iast": "atha", "meaning": "Now"},
            {"sanskrit_combined": "कस्मादुच्यत", "sanskrit_split": "कस्मात् + उच्यते", "iast": "kasmāducyata", "meaning": "Why is it called"},
            {"sanskrit_combined": "ओङ्कारो", "sanskrit_split": "ओङ्कारः", "iast": "oṅkāro", "meaning": "Omkara"},
            {"sanskrit_combined": "यस्मादुच्चार्यमाण", "sanskrit_split": "यस्मात् + उच्चार्यमाणः", "iast": "yasmāduccāryamāṇa", "meaning": "Because being pronounced"},
            {"sanskrit_combined": "एव", "sanskrit_split": "एव", "iast": "eva", "meaning": "Indeed"},
            {"sanskrit_combined": "प्राणानूर्ध्वमुत्क्रामयति", "sanskrit_split": "प्राणान् + ऊर्ध्वम् + उत्क्रामयति", "iast": "prāṇānūrdhvamutkrāmayati", "meaning": "Vital breaths upward sends"},
            {"sanskrit_combined": "तस्मादुच्यत", "sanskrit_split": "तस्मात् + उच्यते", "iast": "tasmāducyata", "meaning": "Therefore is called"},
            {"sanskrit_combined": "ओङ्कारः", "sanskrit_split": "ओङ्कारः", "iast": "oṅkāraḥ", "meaning": "Omkara"},
            {"sanskrit_combined": "अथ", "sanskrit_split": "अथ", "iast": "atha", "meaning": "Now"},
            {"sanskrit_combined": "कस्मादुच्यते", "sanskrit_split": "कस्मात् + उच्यते", "iast": "kasmāducyate", "meaning": "Why is it called"},
            {"sanskrit_combined": "प्रणवो", "sanskrit_split": "प्रणवः", "iast": "praṇavo", "meaning": "Pranava"},
            {"sanskrit_combined": "यस्मादुच्चार्यमाण", "sanskrit_split": "यस्मात् + उच्चार्यमाणः", "iast": "yasmāduccāryamāṇa", "meaning": "Because being pronounced"},
            {"sanskrit_combined": "एव", "sanskrit_split": "एव", "iast": "eva", "meaning": "Indeed"},
            {"sanskrit_combined": "ऋग्यजुःसामाथर्वाङ्गिरसो", "sanskrit_split": "ऋक्-यजुः-साम-अथर्वाङ्गिरसः", "iast": "ṛgyajuḥsāmātharvāṅgiraso", "meaning": "Rig, Yajur, Sama, Atharvangirasa"},
            {"sanskrit_combined": "ब्रह्म", "sanskrit_split": "ब्रह्म", "iast": "brahma", "meaning": "Brahman"},
            {"sanskrit_combined": "ब्राह्मणेभ्यः", "sanskrit_split": "ब्राह्मणेभ्यः", "iast": "brāhmaṇebhyaḥ", "meaning": "To the Brahmanas"},
            {"sanskrit_combined": "प्रणामयति", "sanskrit_split": "प्रणामयति", "iast": "praṇāmayati", "meaning": "Makes bow down"},
            {"sanskrit_combined": "तस्मादुच्यते", "sanskrit_split": "तस्मात् + उच्यते", "iast": "tasmāducyate", "meaning": "Therefore is called"},
            {"sanskrit_combined": "प्रणवः", "sanskrit_split": "प्रणवः", "iast": "praṇavaḥ", "meaning": "Pranava"},
            {"sanskrit_combined": "अथ", "sanskrit_split": "अथ", "iast": "atha", "meaning": "Now"},
            {"sanskrit_combined": "कस्मादुच्यते", "sanskrit_split": "कस्मात् + उच्यते", "iast": "kasmāducyate", "meaning": "Why is it called"},
            {"sanskrit_combined": "सर्वव्यापी", "sanskrit_split": "सर्वव्यापी", "iast": "sarvavyāpī", "meaning": "All-Pervading"},
            {"sanskrit_combined": "यस्मादुच्चार्यमाण", "sanskrit_split": "यस्मात् + उच्चार्यमाणः", "iast": "yasmāduccāryamāṇa", "meaning": "Because being pronounced"},
            {"sanskrit_combined": "एव", "sanskrit_split": "एव", "iast": "eva", "meaning": "Indeed"},
            {"sanskrit_combined": "सर्वान्", "sanskrit_split": "सर्वान्", "iast": "sarvān", "meaning": "All"},
            {"sanskrit_combined": "लोकान्", "sanskrit_split": "लोकान्", "iast": "lokān", "meaning": "Worlds"},
            {"sanskrit_combined": "व्याप्नोति", "sanskrit_split": "व्याप्नोति", "iast": "vyāpnoti", "meaning": "Pervades"},
            {"sanskrit_combined": "तस्मादुच्यते", "sanskrit_split": "तस्मात् + उच्यते", "iast": "tasmāducyate", "meaning": "Therefore is called"},
            {"sanskrit_combined": "सर्वव्यापी", "sanskrit_split": "सर्वव्यापी", "iast": "sarvavyāpī", "meaning": "All-Pervading"},
            {"sanskrit_combined": "अथ", "sanskrit_split": "अथ", "iast": "atha", "meaning": "Now"},
            {"sanskrit_combined": "कस्मादुच्यतेऽनन्तो", "sanskrit_split": "कस्मात् + उच्यते + अनन्तः", "iast": "kasmāducyate'nanto", "meaning": "Why is called Endless"},
            {"sanskrit_combined": "यस्मादुच्चार्यमाण", "sanskrit_split": "यस्मात् + उच्चार्यमाणः", "iast": "yasmāduccāryamāṇa", "meaning": "Because being pronounced"},
            {"sanskrit_combined": "एवाद्यन्तं", "sanskrit_split": "एव + आदि-अन्तम्", "iast": "evādyantaṃ", "meaning": "Indeed beginning and end"},
            {"sanskrit_combined": "नोपलभ्यते", "sanskrit_split": "न + उपलभ्यते", "iast": "nopalabhyate", "meaning": "Not is found"},
            {"sanskrit_combined": "तस्मादुच्यतेऽनन्तः", "sanskrit_split": "तस्मात् + उच्यते + अनन्तः", "iast": "tasmāducyate'nantaḥ", "meaning": "Therefore is called Endless"},
            {"sanskrit_combined": "अथ", "sanskrit_split": "अथ", "iast": "atha", "meaning": "Now"},
            {"sanskrit_combined": "कस्मादुच्यते", "sanskrit_split": "कस्मात् + उच्यते", "iast": "kasmāducyate", "meaning": "Why is it called"},
            {"sanskrit_combined": "तारं", "sanskrit_split": "तारम्", "iast": "tāraṃ", "meaning": "Tara"},
            {"sanskrit_combined": "यस्मादुच्चार्यमाण", "sanskrit_split": "यस्मात् + उच्चार्यमाणः", "iast": "yasmāduccāryamāṇa", "meaning": "Because being pronounced"},
            {"sanskrit_combined": "एव", "sanskrit_split": "एव", "iast": "eva", "meaning": "Indeed"},
            {"sanskrit_combined": "गर्भजन्मव्याधिजरामरणसंसारमहाभयात्तारयति", "sanskrit_split": "गर्भ-जन्म-व्याधि-जरा-मरण-संसार-महा-भयात् + तारयति", "iast": "garbhajanmavyādhijarāmaraṇasaṃsāramahābhayāttārayati", "meaning": "From great fear of conception, birth, disease, old age, death, world helps cross over"},
            {"sanskrit_combined": "त्रायते", "sanskrit_split": "त्रायते", "iast": "trāyate", "meaning": "Protects"},
            {"sanskrit_combined": "च", "sanskrit_split": "च", "iast": "ca", "meaning": "And"},
            {"sanskrit_combined": "तस्मादुच्यते", "sanskrit_split": "तस्मात् + उच्यते", "iast": "tasmāducyate", "meaning": "Therefore is called"},
            {"sanskrit_combined": "तारम्", "sanskrit_split": "तारम्", "iast": "tāram", "meaning": "Tara"}
        ]
    },
    {
        "shloka_number": 9,
        "full_sanskrit": "अथ कस्मादुच्यते शुक्लं यस्मादुच्चार्यमाण एव क्रान्ततेजते तस्मादुच्यते शुक्लम् । अथ कस्मादुच्यते सूक्ष्मं यस्मादुच्चार्यमाण एव सूक्ष्मो भूत्वा शरीराण्यधितिष्ठति सर्वगात्राणि चाभिमृशति तस्मादुच्यते सूक्ष्मम् । अथ कस्मादुच्यते वैद्युतं यस्मादुच्चार्यमाण एवाव्यक्ते महति तमसि द्योतते तस्मादुच्यते वैद्युतम् । अथ कस्मादुच्यते परं ब्रह्म यस्मात्परमपरं परायणं च बृहद्बृहत्या च तस्मादुच्यते परं ब्रह्म । अथ कस्मादुच्यते एको यः सर्वान् प्राणान् सम्भक्ष्य सञ्भक्ष्याजेनानुसृजते तस्मादुच्यते एकः । अथ कस्मादुच्यते रुद्रो यस्मादृषिभिर्नानाविध्यैर्भक्तैर्द्रुतमस्य रूपमुपलभ्यते तस्मादुच्यते रुद्रः । अथ कस्मादुच्यते ईशानो यः सर्वान् देवान् ईशते ईशानीभिर्जननीभिश्च तस्मादुच्यते ईशानः । अथ कस्मादुच्यते भगवान् महेश्वरो यस्माद्भक्ता ज्ञानेन भजन्त्यनुगृह्णाति च वाचं सञ्जयति तस्मादुच्यते भगवान्महेश्वरः । तदेतद्रुद्रचरितम् ॥ ४॥",
        "sandhi_split_sanskrit": "अथ कस्मात् उच्यते शुक्लम् यस्मात् उच्चार्यमाणः एव क्रान्त-तेजते तस्मात् उच्यते शुक्लम् । अथ कस्मात् उच्यते सूक्ष्मम् यस्मात् उच्चार्यमाणः एव सूक्ष्मः भूत्वा शरीराणि अधितिष्ठति सर्व-गात्राणि च अभिमृशति तस्मात् उच्यते सूक्ष्मम् । अथ कस्मात् उच्यते वैद्युतम् यस्मात् उच्चार्यमाणः एव अव्यक्ते महति तमसि द्योतते तस्मात् उच्यते वैद्युतम् । अथ कस्मात् उच्यते परम् ब्रह्म यस्मात् परम-अपरम् परायणम् च बृहत्-बृहत्या च तस्मात् उच्यते परम् ब्रह्म । अथ कस्मात् उच्यते एकः यः सर्वान् प्राणान् सम्भक्ष्य सञ्भक्ष्य-अजेन अनुसृजते तस्मात् उच्यते एकः । अथ कस्मात् उच्यते रुद्रः यस्मात् ऋषिभिः नाना-विध्यैः भक्तैः द्रुतम् अस्य रूपम् उपलभ्यते तस्मात् उच्यते रुद्रः । अथ कस्मात् उच्यते ईशानः यः सर्वान् देवान् ईशते ईशानीभिः जननीभिः च तस्मात् उच्यते ईशानः । अथ कस्मात् उच्यते भगवान् महेश्वरः यस्मात् भक्ताः ज्ञानेन भजन्ति अनुगृह्णाति च वाचम् सञ्जयति तस्मात् उच्यते भगवान् महेश्वरः । तत् एतत् रुद्र-चरितम् ॥ ४॥",
        "iast_transliteration": "atha kasmāducyate śuklaṃ yasmāduccāryamāṇa eva krāntatejate tasmāducyate śuklam | atha kasmāducyate sūkṣmaṃ yasmāduccāryamāṇa eva sūkṣmo bhūtvā śarīrāṇyadhitiṣṭhati sarvagātrāṇi cābhimṛśati tasmāducyate sūkṣmam | atha kasmāducyate vaidyutaṃ yasmāduccāryamāṇa evāvyakte mahati tamasi dyotate tasmāducyate vaidyutam | atha kasmāducyate paraṃ brahma yasmātparamaparaṃ parāyaṇaṃ ca bṛhadbṛhatyā ca tasmāducyate paraṃ brahma | atha kasmāducyate eko yaḥ sarvān prāṇān sambhakṣya sañbhakṣyājenānusṛjate tasmāducyate ekaḥ | atha kasmāducyate rudro yasmādṛṣibhirnānāvidhyairbhaktairdrutamasya rūpamupalabhyate tasmāducyate rudraḥ | atha kasmāducyate īśāno yaḥ sarvān devān īśate īśānībhirjananībhiśca tasmāducyate īśānaḥ | atha kasmāducyate bhagavān maheśvaro yasmādbhaktā jñānena bhajantyanugṛhṇāti ca vācaṃ sañjayati tasmāducyate bhagavānmaheśvaraḥ | tadetadrudracaritam || 4||",
        "meaning_english": "Now why is it called White? Because... (etc. defining Shuklam, Sukshmam, Vaidyutam, Param Brahma, Ekah, Rudrah, Ishanah, Bhagavan Mahesvarah). That is this account of Rudra. (4)",
        "meaning_hindi": None,
        "audio_start_ms": 90000,
        "audio_end_ms": 100000,
        "padas": [
            {"sanskrit_combined": "अथ", "sanskrit_split": "अथ", "iast": "atha", "meaning": "Now"}
        ]
    },
    {
        "shloka_number": 10,
        "full_sanskrit": "एको ह देवः प्रदिशो नु सर्वाः पूर्वो ह जातः स उ गर्भे अन्तः । स एव जातः स जनिष्यमाणः प्रत्यञ्जनास्तिष्ठति सर्वतोमुखः ॥ एकस्तथा भुवनस्यास्य गोप्ता य एवैको विश्वमथं सृजति । इत्युपनिषत् ॥ ॐ शान्तिः शान्तिः शान्तिः ॥",
        "sandhi_split_sanskrit": "एकः ह देवः प्रदिशः नु सर्वाः पूर्वः ह जातः सः उ गर्भे अन्तः । सः एव जातः सः जनिष्यमाणः प्रत्यञ्-जनाः तिष्ठति सर्वतः-मुखः ॥ एकः तथा भुवनस्य अस्य गोप्ता यः एव एकः विश्वम् अथम् सृजति । इति उपनिषत् ॥ ॐ शान्तिः शान्तिः शान्तिः ॥",
        "iast_transliteration": "eko ha devaḥ pradiśo nu sarvāḥ pūrvo ha jātaḥ sa u garbhe antaḥ | sa eva jātaḥ sa janiṣyamāṇaḥ pratyañjanāstiṣṭhati sarvatomukhaḥ || ekastathā bhuvanasyāsya goptā ya evaiko viśvamathaṃ sṛjati | ityupaniṣat || oṃ śāntiḥ śāntiḥ śāntiḥ ||",
        "meaning_english": "One indeed is the God, extending in all directions. He was born before, and He is within the womb. He alone is born, He will be born. He stands facing all beings, facing all directions. One thus is the protector of this world, who alone creates the universe. Thus the Upanishad. Om Peace! Peace! Peace!",
        "meaning_hindi": None,
        "audio_start_ms": 100000,
        "audio_end_ms": 110000,
        "padas": [
            {"sanskrit_combined": "एको", "sanskrit_split": "एकः", "iast": "eko", "meaning": "One"},
            {"sanskrit_combined": "ह", "sanskrit_split": "ह", "iast": "ha", "meaning": "Indeed"},
            {"sanskrit_combined": "देवः", "sanskrit_split": "देवः", "iast": "devaḥ", "meaning": "God"},
            {"sanskrit_combined": "प्रदिशो", "sanskrit_split": "प्रदिशः", "iast": "pradiśo", "meaning": "Directions"},
            {"sanskrit_combined": "नु", "sanskrit_split": "नु", "iast": "nu", "meaning": "Indeed"},
            {"sanskrit_combined": "सर्वाः", "sanskrit_split": "सर्वाः", "iast": "sarvāḥ", "meaning": "All"},
            {"sanskrit_combined": "पूर्वो", "sanskrit_split": "पूर्वः", "iast": "pūrvo", "meaning": "Before"},
            {"sanskrit_combined": "ह", "sanskrit_split": "ह", "iast": "ha", "meaning": "Indeed"},
            {"sanskrit_combined": "जातः", "sanskrit_split": "जातः", "iast": "jātaḥ", "meaning": "Born"},
            {"sanskrit_combined": "स", "sanskrit_split": "सः", "iast": "sa", "meaning": "He"},
            {"sanskrit_combined": "उ", "sanskrit_split": "उ", "iast": "u", "meaning": "Indeed"},
            {"sanskrit_combined": "गर्भे", "sanskrit_split": "गर्भे", "iast": "garbhe", "meaning": "In the womb"},
            {"sanskrit_combined": "अन्तः", "sanskrit_split": "अन्तः", "iast": "antaḥ", "meaning": "Within"},
            {"sanskrit_combined": "स", "sanskrit_split": "सः", "iast": "sa", "meaning": "He"},
            {"sanskrit_combined": "एव", "sanskrit_split": "एव", "iast": "eva", "meaning": "Alone"},
            {"sanskrit_combined": "जातः", "sanskrit_split": "जातः", "iast": "jātaḥ", "meaning": "Born"},
            {"sanskrit_combined": "स", "sanskrit_split": "सः", "iast": "sa", "meaning": "He"},
            {"sanskrit_combined": "जनिष्यमाणः", "sanskrit_split": "जनिष्यमाणः", "iast": "janiṣyamāṇaḥ", "meaning": "Will be born"},
            {"sanskrit_combined": "प्रत्यञ्जनास्तिष्ठति", "sanskrit_split": "प्रत्यञ्-जनाः + तिष्ठति", "iast": "pratyañjanāstiṣṭhati", "meaning": "Facing beings stands"},
            {"sanskrit_combined": "सर्वतोमुखः", "sanskrit_split": "सर्वतः-मुखः", "iast": "sarvatomukhaḥ", "meaning": "Facing all directions"},
            {"sanskrit_combined": "एकस्तथा", "sanskrit_split": "एकः + तथा", "iast": "ekastathā", "meaning": "One thus"},
            {"sanskrit_combined": "भुवनस्यास्य", "sanskrit_split": "भुवनस्य + अस्य", "iast": "bhuvanasyāsya", "meaning": "Of this world"},
            {"sanskrit_combined": "गोप्ता", "sanskrit_split": "गोप्ता", "iast": "goptā", "meaning": "Protector"},
            {"sanskrit_combined": "य", "sanskrit_split": "यः", "iast": "ya", "meaning": "Who"},
            {"sanskrit_combined": "एवैको", "sanskrit_split": "एव + एकः", "iast": "evaiko", "meaning": "Alone one"},
            {"sanskrit_combined": "विश्वमथं", "sanskrit_split": "विश्वम् + अथम्", "iast": "viśvamathaṃ", "meaning": "Universe creates"},
            {"sanskrit_combined": "सृजति", "sanskrit_split": "सृजति", "iast": "sṛjati", "meaning": "Creates"},
            {"sanskrit_combined": "इत्युपनिषत्", "sanskrit_split": "इति + उपनिषत्", "iast": "ityupaniṣat", "meaning": "Thus the Upanishad"},
            {"sanskrit_combined": "ॐ", "sanskrit_split": "ॐ", "iast": "oṃ", "meaning": "Om"},
            {"sanskrit_combined": "शान्तिः", "sanskrit_split": "शान्तिः", "iast": "śāntiḥ", "meaning": "Peace"},
            {"sanskrit_combined": "शान्तिः", "sanskrit_split": "शान्तिः", "iast": "śāntiḥ", "meaning": "Peace"},
            {"sanskrit_combined": "शान्तिः", "sanskrit_split": "शान्तिः", "iast": "śāntiḥ", "meaning": "Peace"}
        ]
    }
]

# Set pada indices and default missing values
for s in shlokas:
    for idx, pada in enumerate(s["padas"]):
        pada["pada_index"] = idx + 1
        pada["sandhi_rule_name"] = None
        pada["sandhi_rule_explanation"] = None
        pada["audio_start_ms"] = s["audio_start_ms"] + idx * 500
        pada["audio_end_ms"] = s["audio_start_ms"] + (idx + 1) * 500

stotra = {
    "stotra": {
        "id": "shiva_atharvashirsha",
        "title_devanagari": "शिव अथर्वशीर्ष",
        "title_english": "Shiva Atharvashirsha",
        "category": "Atharvashirsha",
        "deity": "Shiva",
        "total_shlokas": 10,
        "description": "Shiva Atharvashirsha Upanishad glorifying Lord Shiva.",
        "audio_asset_path": None
    },
    "shlokas": shlokas
}

out_path = "/Users/dhruvvarachhiya/Documents/Portfolio/Sahasranamam-Tutorial-main/app/src/main/assets/stotras/shiva_atharvashirsha.json"
os.makedirs(os.path.dirname(out_path), exist_ok=True)
with open(out_path, "w", encoding="utf-8") as f:
    json.dump(stotra, f, ensure_ascii=False, indent=2)

print("Generated shiva_atharvashirsha.json")
